// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.2
// source: statistic/grpc/config.proto

package service

import (
	statistic "github.com/Asutorufa/yuhaiin/pkg/protos/statistic"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Counter struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Download    uint64                 `protobuf:"varint,1,opt,name=download"`
	xxx_hidden_Upload      uint64                 `protobuf:"varint,2,opt,name=upload"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Counter) Reset() {
	*x = Counter{}
	mi := &file_statistic_grpc_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counter) ProtoMessage() {}

func (x *Counter) ProtoReflect() protoreflect.Message {
	mi := &file_statistic_grpc_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Counter) GetDownload() uint64 {
	if x != nil {
		return x.xxx_hidden_Download
	}
	return 0
}

func (x *Counter) GetUpload() uint64 {
	if x != nil {
		return x.xxx_hidden_Upload
	}
	return 0
}

func (x *Counter) SetDownload(v uint64) {
	x.xxx_hidden_Download = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Counter) SetUpload(v uint64) {
	x.xxx_hidden_Upload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Counter) HasDownload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Counter) HasUpload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Counter) ClearDownload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Download = 0
}

func (x *Counter) ClearUpload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Upload = 0
}

type Counter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Download *uint64
	Upload   *uint64
}

func (b0 Counter_builder) Build() *Counter {
	m0 := &Counter{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Download != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Download = *b.Download
	}
	if b.Upload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Upload = *b.Upload
	}
	return m0
}

type TotalFlow struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Download    uint64                 `protobuf:"varint,1,opt,name=download"`
	xxx_hidden_Upload      uint64                 `protobuf:"varint,2,opt,name=upload"`
	xxx_hidden_Counters    map[uint64]*Counter    `protobuf:"bytes,3,rep,name=counters" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TotalFlow) Reset() {
	*x = TotalFlow{}
	mi := &file_statistic_grpc_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalFlow) ProtoMessage() {}

func (x *TotalFlow) ProtoReflect() protoreflect.Message {
	mi := &file_statistic_grpc_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TotalFlow) GetDownload() uint64 {
	if x != nil {
		return x.xxx_hidden_Download
	}
	return 0
}

func (x *TotalFlow) GetUpload() uint64 {
	if x != nil {
		return x.xxx_hidden_Upload
	}
	return 0
}

func (x *TotalFlow) GetCounters() map[uint64]*Counter {
	if x != nil {
		return x.xxx_hidden_Counters
	}
	return nil
}

func (x *TotalFlow) SetDownload(v uint64) {
	x.xxx_hidden_Download = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *TotalFlow) SetUpload(v uint64) {
	x.xxx_hidden_Upload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *TotalFlow) SetCounters(v map[uint64]*Counter) {
	x.xxx_hidden_Counters = v
}

func (x *TotalFlow) HasDownload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TotalFlow) HasUpload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TotalFlow) ClearDownload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Download = 0
}

func (x *TotalFlow) ClearUpload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Upload = 0
}

type TotalFlow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Download *uint64
	Upload   *uint64
	Counters map[uint64]*Counter
}

func (b0 TotalFlow_builder) Build() *TotalFlow {
	m0 := &TotalFlow{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Download != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Download = *b.Download
	}
	if b.Upload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Upload = *b.Upload
	}
	x.xxx_hidden_Counters = b.Counters
	return m0
}

type NotifyData struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data isNotifyData_Data      `protobuf_oneof:"data"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NotifyData) Reset() {
	*x = NotifyData{}
	mi := &file_statistic_grpc_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyData) ProtoMessage() {}

func (x *NotifyData) ProtoReflect() protoreflect.Message {
	mi := &file_statistic_grpc_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NotifyData) GetTotalFlow() *TotalFlow {
	if x != nil {
		if x, ok := x.xxx_hidden_Data.(*notifyData_TotalFlow); ok {
			return x.TotalFlow
		}
	}
	return nil
}

func (x *NotifyData) GetNotifyNewConnections() *NotifyNewConnections {
	if x != nil {
		if x, ok := x.xxx_hidden_Data.(*notifyData_NotifyNewConnections); ok {
			return x.NotifyNewConnections
		}
	}
	return nil
}

func (x *NotifyData) GetNotifyRemoveConnections() *NotifyRemoveConnections {
	if x != nil {
		if x, ok := x.xxx_hidden_Data.(*notifyData_NotifyRemoveConnections); ok {
			return x.NotifyRemoveConnections
		}
	}
	return nil
}

func (x *NotifyData) SetTotalFlow(v *TotalFlow) {
	if v == nil {
		x.xxx_hidden_Data = nil
		return
	}
	x.xxx_hidden_Data = &notifyData_TotalFlow{v}
}

func (x *NotifyData) SetNotifyNewConnections(v *NotifyNewConnections) {
	if v == nil {
		x.xxx_hidden_Data = nil
		return
	}
	x.xxx_hidden_Data = &notifyData_NotifyNewConnections{v}
}

func (x *NotifyData) SetNotifyRemoveConnections(v *NotifyRemoveConnections) {
	if v == nil {
		x.xxx_hidden_Data = nil
		return
	}
	x.xxx_hidden_Data = &notifyData_NotifyRemoveConnections{v}
}

func (x *NotifyData) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *NotifyData) HasTotalFlow() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Data.(*notifyData_TotalFlow)
	return ok
}

func (x *NotifyData) HasNotifyNewConnections() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Data.(*notifyData_NotifyNewConnections)
	return ok
}

func (x *NotifyData) HasNotifyRemoveConnections() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Data.(*notifyData_NotifyRemoveConnections)
	return ok
}

func (x *NotifyData) ClearData() {
	x.xxx_hidden_Data = nil
}

func (x *NotifyData) ClearTotalFlow() {
	if _, ok := x.xxx_hidden_Data.(*notifyData_TotalFlow); ok {
		x.xxx_hidden_Data = nil
	}
}

func (x *NotifyData) ClearNotifyNewConnections() {
	if _, ok := x.xxx_hidden_Data.(*notifyData_NotifyNewConnections); ok {
		x.xxx_hidden_Data = nil
	}
}

func (x *NotifyData) ClearNotifyRemoveConnections() {
	if _, ok := x.xxx_hidden_Data.(*notifyData_NotifyRemoveConnections); ok {
		x.xxx_hidden_Data = nil
	}
}

const NotifyData_Data_not_set_case case_NotifyData_Data = 0
const NotifyData_TotalFlow_case case_NotifyData_Data = 3
const NotifyData_NotifyNewConnections_case case_NotifyData_Data = 1
const NotifyData_NotifyRemoveConnections_case case_NotifyData_Data = 2

func (x *NotifyData) WhichData() case_NotifyData_Data {
	if x == nil {
		return NotifyData_Data_not_set_case
	}
	switch x.xxx_hidden_Data.(type) {
	case *notifyData_TotalFlow:
		return NotifyData_TotalFlow_case
	case *notifyData_NotifyNewConnections:
		return NotifyData_NotifyNewConnections_case
	case *notifyData_NotifyRemoveConnections:
		return NotifyData_NotifyRemoveConnections_case
	default:
		return NotifyData_Data_not_set_case
	}
}

type NotifyData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Data:
	TotalFlow               *TotalFlow
	NotifyNewConnections    *NotifyNewConnections
	NotifyRemoveConnections *NotifyRemoveConnections
	// -- end of xxx_hidden_Data
}

func (b0 NotifyData_builder) Build() *NotifyData {
	m0 := &NotifyData{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TotalFlow != nil {
		x.xxx_hidden_Data = &notifyData_TotalFlow{b.TotalFlow}
	}
	if b.NotifyNewConnections != nil {
		x.xxx_hidden_Data = &notifyData_NotifyNewConnections{b.NotifyNewConnections}
	}
	if b.NotifyRemoveConnections != nil {
		x.xxx_hidden_Data = &notifyData_NotifyRemoveConnections{b.NotifyRemoveConnections}
	}
	return m0
}

type case_NotifyData_Data protoreflect.FieldNumber

func (x case_NotifyData_Data) String() string {
	md := file_statistic_grpc_config_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isNotifyData_Data interface {
	isNotifyData_Data()
}

type notifyData_TotalFlow struct {
	TotalFlow *TotalFlow `protobuf:"bytes,3,opt,name=total_flow,json=totalFlow,oneof"`
}

type notifyData_NotifyNewConnections struct {
	NotifyNewConnections *NotifyNewConnections `protobuf:"bytes,1,opt,name=notify_new_connections,json=notifyNewConnections,oneof"`
}

type notifyData_NotifyRemoveConnections struct {
	NotifyRemoveConnections *NotifyRemoveConnections `protobuf:"bytes,2,opt,name=notify_remove_connections,json=notifyRemoveConnections,oneof"`
}

func (*notifyData_TotalFlow) isNotifyData_Data() {}

func (*notifyData_NotifyNewConnections) isNotifyData_Data() {}

func (*notifyData_NotifyRemoveConnections) isNotifyData_Data() {}

type NotifyNewConnections struct {
	state                  protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Connections *[]*statistic.Connection `protobuf:"bytes,1,rep,name=connections"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NotifyNewConnections) Reset() {
	*x = NotifyNewConnections{}
	mi := &file_statistic_grpc_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNewConnections) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNewConnections) ProtoMessage() {}

func (x *NotifyNewConnections) ProtoReflect() protoreflect.Message {
	mi := &file_statistic_grpc_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NotifyNewConnections) GetConnections() []*statistic.Connection {
	if x != nil {
		if x.xxx_hidden_Connections != nil {
			return *x.xxx_hidden_Connections
		}
	}
	return nil
}

func (x *NotifyNewConnections) SetConnections(v []*statistic.Connection) {
	x.xxx_hidden_Connections = &v
}

type NotifyNewConnections_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Connections []*statistic.Connection
}

func (b0 NotifyNewConnections_builder) Build() *NotifyNewConnections {
	m0 := &NotifyNewConnections{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Connections = &b.Connections
	return m0
}

type NotifyRemoveConnections struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ids []uint64               `protobuf:"varint,1,rep,packed,name=ids"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotifyRemoveConnections) Reset() {
	*x = NotifyRemoveConnections{}
	mi := &file_statistic_grpc_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRemoveConnections) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRemoveConnections) ProtoMessage() {}

func (x *NotifyRemoveConnections) ProtoReflect() protoreflect.Message {
	mi := &file_statistic_grpc_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NotifyRemoveConnections) GetIds() []uint64 {
	if x != nil {
		return x.xxx_hidden_Ids
	}
	return nil
}

func (x *NotifyRemoveConnections) SetIds(v []uint64) {
	x.xxx_hidden_Ids = v
}

type NotifyRemoveConnections_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ids []uint64
}

func (b0 NotifyRemoveConnections_builder) Build() *NotifyRemoveConnections {
	m0 := &NotifyRemoveConnections{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ids = b.Ids
	return m0
}

type FailedHistory struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Protocol    *string                `protobuf:"bytes,1,opt,name=protocol"`
	xxx_hidden_Host        *string                `protobuf:"bytes,2,opt,name=host"`
	xxx_hidden_Error       *string                `protobuf:"bytes,3,opt,name=error"`
	xxx_hidden_Process     *string                `protobuf:"bytes,4,opt,name=process"`
	xxx_hidden_Time        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time"`
	xxx_hidden_FailedCount uint64                 `protobuf:"varint,6,opt,name=failed_count"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FailedHistory) Reset() {
	*x = FailedHistory{}
	mi := &file_statistic_grpc_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailedHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedHistory) ProtoMessage() {}

func (x *FailedHistory) ProtoReflect() protoreflect.Message {
	mi := &file_statistic_grpc_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FailedHistory) GetProtocol() string {
	if x != nil {
		if x.xxx_hidden_Protocol != nil {
			return *x.xxx_hidden_Protocol
		}
		return ""
	}
	return ""
}

func (x *FailedHistory) GetHost() string {
	if x != nil {
		if x.xxx_hidden_Host != nil {
			return *x.xxx_hidden_Host
		}
		return ""
	}
	return ""
}

func (x *FailedHistory) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *FailedHistory) GetProcess() string {
	if x != nil {
		if x.xxx_hidden_Process != nil {
			return *x.xxx_hidden_Process
		}
		return ""
	}
	return ""
}

func (x *FailedHistory) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Time
	}
	return nil
}

func (x *FailedHistory) GetFailedCount() uint64 {
	if x != nil {
		return x.xxx_hidden_FailedCount
	}
	return 0
}

func (x *FailedHistory) SetProtocol(v string) {
	x.xxx_hidden_Protocol = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *FailedHistory) SetHost(v string) {
	x.xxx_hidden_Host = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *FailedHistory) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *FailedHistory) SetProcess(v string) {
	x.xxx_hidden_Process = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *FailedHistory) SetTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_Time = v
}

func (x *FailedHistory) SetFailedCount(v uint64) {
	x.xxx_hidden_FailedCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *FailedHistory) HasProtocol() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *FailedHistory) HasHost() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *FailedHistory) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *FailedHistory) HasProcess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *FailedHistory) HasTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Time != nil
}

func (x *FailedHistory) HasFailedCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *FailedHistory) ClearProtocol() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Protocol = nil
}

func (x *FailedHistory) ClearHost() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Host = nil
}

func (x *FailedHistory) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Error = nil
}

func (x *FailedHistory) ClearProcess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Process = nil
}

func (x *FailedHistory) ClearTime() {
	x.xxx_hidden_Time = nil
}

func (x *FailedHistory) ClearFailedCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_FailedCount = 0
}

type FailedHistory_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Protocol    *string
	Host        *string
	Error       *string
	Process     *string
	Time        *timestamppb.Timestamp
	FailedCount *uint64
}

func (b0 FailedHistory_builder) Build() *FailedHistory {
	m0 := &FailedHistory{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Protocol != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Protocol = b.Protocol
	}
	if b.Host != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Host = b.Host
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Error = b.Error
	}
	if b.Process != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Process = b.Process
	}
	x.xxx_hidden_Time = b.Time
	if b.FailedCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_FailedCount = *b.FailedCount
	}
	return m0
}

type FailedHistoryList struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Objects            *[]*FailedHistory      `protobuf:"bytes,1,rep,name=objects"`
	xxx_hidden_DumpProcessEnabled bool                   `protobuf:"varint,2,opt,name=dump_process_enabled"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *FailedHistoryList) Reset() {
	*x = FailedHistoryList{}
	mi := &file_statistic_grpc_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailedHistoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedHistoryList) ProtoMessage() {}

func (x *FailedHistoryList) ProtoReflect() protoreflect.Message {
	mi := &file_statistic_grpc_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FailedHistoryList) GetObjects() []*FailedHistory {
	if x != nil {
		if x.xxx_hidden_Objects != nil {
			return *x.xxx_hidden_Objects
		}
	}
	return nil
}

func (x *FailedHistoryList) GetDumpProcessEnabled() bool {
	if x != nil {
		return x.xxx_hidden_DumpProcessEnabled
	}
	return false
}

func (x *FailedHistoryList) SetObjects(v []*FailedHistory) {
	x.xxx_hidden_Objects = &v
}

func (x *FailedHistoryList) SetDumpProcessEnabled(v bool) {
	x.xxx_hidden_DumpProcessEnabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *FailedHistoryList) HasDumpProcessEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *FailedHistoryList) ClearDumpProcessEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DumpProcessEnabled = false
}

type FailedHistoryList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Objects            []*FailedHistory
	DumpProcessEnabled *bool
}

func (b0 FailedHistoryList_builder) Build() *FailedHistoryList {
	m0 := &FailedHistoryList{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Objects = &b.Objects
	if b.DumpProcessEnabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_DumpProcessEnabled = *b.DumpProcessEnabled
	}
	return m0
}

type AllHistory struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Connection  *statistic.Connection  `protobuf:"bytes,1,opt,name=connection"`
	xxx_hidden_Count       uint64                 `protobuf:"varint,2,opt,name=count"`
	xxx_hidden_Time        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AllHistory) Reset() {
	*x = AllHistory{}
	mi := &file_statistic_grpc_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllHistory) ProtoMessage() {}

func (x *AllHistory) ProtoReflect() protoreflect.Message {
	mi := &file_statistic_grpc_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AllHistory) GetConnection() *statistic.Connection {
	if x != nil {
		return x.xxx_hidden_Connection
	}
	return nil
}

func (x *AllHistory) GetCount() uint64 {
	if x != nil {
		return x.xxx_hidden_Count
	}
	return 0
}

func (x *AllHistory) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Time
	}
	return nil
}

func (x *AllHistory) SetConnection(v *statistic.Connection) {
	x.xxx_hidden_Connection = v
}

func (x *AllHistory) SetCount(v uint64) {
	x.xxx_hidden_Count = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *AllHistory) SetTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_Time = v
}

func (x *AllHistory) HasConnection() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Connection != nil
}

func (x *AllHistory) HasCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AllHistory) HasTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Time != nil
}

func (x *AllHistory) ClearConnection() {
	x.xxx_hidden_Connection = nil
}

func (x *AllHistory) ClearCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Count = 0
}

func (x *AllHistory) ClearTime() {
	x.xxx_hidden_Time = nil
}

type AllHistory_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Connection *statistic.Connection
	Count      *uint64
	Time       *timestamppb.Timestamp
}

func (b0 AllHistory_builder) Build() *AllHistory {
	m0 := &AllHistory{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Connection = b.Connection
	if b.Count != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Count = *b.Count
	}
	x.xxx_hidden_Time = b.Time
	return m0
}

type AllHistoryList struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Objects            *[]*AllHistory         `protobuf:"bytes,1,rep,name=objects"`
	xxx_hidden_DumpProcessEnabled bool                   `protobuf:"varint,2,opt,name=dump_process_enabled"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *AllHistoryList) Reset() {
	*x = AllHistoryList{}
	mi := &file_statistic_grpc_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllHistoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllHistoryList) ProtoMessage() {}

func (x *AllHistoryList) ProtoReflect() protoreflect.Message {
	mi := &file_statistic_grpc_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AllHistoryList) GetObjects() []*AllHistory {
	if x != nil {
		if x.xxx_hidden_Objects != nil {
			return *x.xxx_hidden_Objects
		}
	}
	return nil
}

func (x *AllHistoryList) GetDumpProcessEnabled() bool {
	if x != nil {
		return x.xxx_hidden_DumpProcessEnabled
	}
	return false
}

func (x *AllHistoryList) SetObjects(v []*AllHistory) {
	x.xxx_hidden_Objects = &v
}

func (x *AllHistoryList) SetDumpProcessEnabled(v bool) {
	x.xxx_hidden_DumpProcessEnabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AllHistoryList) HasDumpProcessEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AllHistoryList) ClearDumpProcessEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DumpProcessEnabled = false
}

type AllHistoryList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Objects            []*AllHistory
	DumpProcessEnabled *bool
}

func (b0 AllHistoryList_builder) Build() *AllHistoryList {
	m0 := &AllHistoryList{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Objects = &b.Objects
	if b.DumpProcessEnabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_DumpProcessEnabled = *b.DumpProcessEnabled
	}
	return m0
}

var File_statistic_grpc_config_proto protoreflect.FileDescriptor

var file_statistic_grpc_config_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x79,
	0x75, 0x68, 0x61, 0x69, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x5f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x80, 0x02, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x5f, 0x66, 0x6c, 0x6f, 0x77, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x56, 0x0a, 0x08, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x79,
	0x75, 0x68, 0x61, 0x69, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x73, 0x1a, 0x66, 0x0a, 0x0d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x79, 0x75, 0x68, 0x61, 0x69, 0x69, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xd1, 0x02, 0x0a, 0x0b, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x12, 0x4d, 0x0a, 0x0a, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x66, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c,
	0x2e, 0x79, 0x75, 0x68, 0x61, 0x69, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x66, 0x6c, 0x6f, 0x77, 0x48, 0x00, 0x52, 0x09,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x46, 0x6c, 0x6f, 0x77, 0x12, 0x70, 0x0a, 0x16, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x5f, 0x6e, 0x65, 0x77, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x79, 0x75, 0x68, 0x61,
	0x69, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x5f, 0x6e, 0x65, 0x77, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x14, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4e, 0x65, 0x77,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x79, 0x0a, 0x19, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3b,
	0x2e, 0x79, 0x75, 0x68, 0x61, 0x69, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x17, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x59,
	0x0a, 0x16, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x6e, 0x65, 0x77, 0x5f, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x79, 0x75, 0x68, 0x61, 0x69, 0x69, 0x6e, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x2d, 0x0a, 0x19, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0xc4, 0x01, 0x0a, 0x0e, 0x66, 0x61, 0x69,
	0x6c, 0x65, 0x64, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2e, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x66,
	0x61, 0x69, 0x6c, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0c, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x95, 0x01, 0x0a, 0x13, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x4a, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x79, 0x75, 0x68, 0x61, 0x69,
	0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x66, 0x61, 0x69, 0x6c,
	0x65, 0x64, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x12, 0x32, 0x0a, 0x14, 0x64, 0x75, 0x6d, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x14, 0x64, 0x75, 0x6d, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x92, 0x01, 0x0a, 0x0b, 0x61, 0x6c, 0x6c, 0x5f,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x3d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x79, 0x75,
	0x68, 0x61, 0x69, 0x69, 0x6e, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x8f, 0x01, 0x0a,
	0x10, 0x61, 0x6c, 0x6c, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x12, 0x47, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x79, 0x75, 0x68, 0x61, 0x69, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x6c, 0x6c, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x32, 0x0a, 0x14, 0x64, 0x75,
	0x6d, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x14, 0x64, 0x75, 0x6d, 0x70, 0x5f, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x32, 0xa9,
	0x04, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x59,
	0x0a, 0x05, 0x63, 0x6f, 0x6e, 0x6e, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x38, 0x2e, 0x79, 0x75, 0x68, 0x61, 0x69, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x6e, 0x65, 0x77, 0x5f, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x61, 0x0a, 0x0a, 0x63, 0x6c, 0x6f,
	0x73, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x12, 0x3b, 0x2e, 0x79, 0x75, 0x68, 0x61, 0x69, 0x69,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4d, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x2c, 0x2e,
	0x79, 0x75, 0x68, 0x61, 0x69, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x66, 0x6c, 0x6f, 0x77, 0x12, 0x51, 0x0a, 0x06, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x2d, 0x2e,
	0x79, 0x75, 0x68, 0x61, 0x69, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x30, 0x01, 0x12, 0x5f,
	0x0a, 0x0e, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x35, 0x2e, 0x79, 0x75, 0x68, 0x61, 0x69,
	0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x66, 0x61, 0x69, 0x6c,
	0x65, 0x64, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x12,
	0x59, 0x0a, 0x0b, 0x61, 0x6c, 0x6c, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x32, 0x2e, 0x79, 0x75, 0x68, 0x61, 0x69, 0x69, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x6c, 0x6c, 0x5f, 0x68, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x43, 0x5a, 0x39, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x73, 0x75, 0x74, 0x6f, 0x72, 0x75,
	0x66, 0x61, 0x2f, 0x79, 0x75, 0x68, 0x61, 0x69, 0x69, 0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x92, 0x03, 0x05, 0xd2, 0x3e, 0x02, 0x10, 0x03, 0x62,
	0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70, 0xe8, 0x07,
})

var file_statistic_grpc_config_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_statistic_grpc_config_proto_goTypes = []any{
	(*Counter)(nil),                 // 0: yuhaiin.protos.statistic.service.counter
	(*TotalFlow)(nil),               // 1: yuhaiin.protos.statistic.service.total_flow
	(*NotifyData)(nil),              // 2: yuhaiin.protos.statistic.service.notify_data
	(*NotifyNewConnections)(nil),    // 3: yuhaiin.protos.statistic.service.notify_new_connections
	(*NotifyRemoveConnections)(nil), // 4: yuhaiin.protos.statistic.service.notify_remove_connections
	(*FailedHistory)(nil),           // 5: yuhaiin.protos.statistic.service.failed_history
	(*FailedHistoryList)(nil),       // 6: yuhaiin.protos.statistic.service.failed_history_list
	(*AllHistory)(nil),              // 7: yuhaiin.protos.statistic.service.all_history
	(*AllHistoryList)(nil),          // 8: yuhaiin.protos.statistic.service.all_history_list
	nil,                             // 9: yuhaiin.protos.statistic.service.total_flow.CountersEntry
	(*statistic.Connection)(nil),    // 10: yuhaiin.statistic.connection
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 12: google.protobuf.Empty
}
var file_statistic_grpc_config_proto_depIdxs = []int32{
	9,  // 0: yuhaiin.protos.statistic.service.total_flow.counters:type_name -> yuhaiin.protos.statistic.service.total_flow.CountersEntry
	1,  // 1: yuhaiin.protos.statistic.service.notify_data.total_flow:type_name -> yuhaiin.protos.statistic.service.total_flow
	3,  // 2: yuhaiin.protos.statistic.service.notify_data.notify_new_connections:type_name -> yuhaiin.protos.statistic.service.notify_new_connections
	4,  // 3: yuhaiin.protos.statistic.service.notify_data.notify_remove_connections:type_name -> yuhaiin.protos.statistic.service.notify_remove_connections
	10, // 4: yuhaiin.protos.statistic.service.notify_new_connections.connections:type_name -> yuhaiin.statistic.connection
	11, // 5: yuhaiin.protos.statistic.service.failed_history.time:type_name -> google.protobuf.Timestamp
	5,  // 6: yuhaiin.protos.statistic.service.failed_history_list.objects:type_name -> yuhaiin.protos.statistic.service.failed_history
	10, // 7: yuhaiin.protos.statistic.service.all_history.connection:type_name -> yuhaiin.statistic.connection
	11, // 8: yuhaiin.protos.statistic.service.all_history.time:type_name -> google.protobuf.Timestamp
	7,  // 9: yuhaiin.protos.statistic.service.all_history_list.objects:type_name -> yuhaiin.protos.statistic.service.all_history
	0,  // 10: yuhaiin.protos.statistic.service.total_flow.CountersEntry.value:type_name -> yuhaiin.protos.statistic.service.counter
	12, // 11: yuhaiin.protos.statistic.service.connections.conns:input_type -> google.protobuf.Empty
	4,  // 12: yuhaiin.protos.statistic.service.connections.close_conn:input_type -> yuhaiin.protos.statistic.service.notify_remove_connections
	12, // 13: yuhaiin.protos.statistic.service.connections.total:input_type -> google.protobuf.Empty
	12, // 14: yuhaiin.protos.statistic.service.connections.notify:input_type -> google.protobuf.Empty
	12, // 15: yuhaiin.protos.statistic.service.connections.failed_history:input_type -> google.protobuf.Empty
	12, // 16: yuhaiin.protos.statistic.service.connections.all_history:input_type -> google.protobuf.Empty
	3,  // 17: yuhaiin.protos.statistic.service.connections.conns:output_type -> yuhaiin.protos.statistic.service.notify_new_connections
	12, // 18: yuhaiin.protos.statistic.service.connections.close_conn:output_type -> google.protobuf.Empty
	1,  // 19: yuhaiin.protos.statistic.service.connections.total:output_type -> yuhaiin.protos.statistic.service.total_flow
	2,  // 20: yuhaiin.protos.statistic.service.connections.notify:output_type -> yuhaiin.protos.statistic.service.notify_data
	6,  // 21: yuhaiin.protos.statistic.service.connections.failed_history:output_type -> yuhaiin.protos.statistic.service.failed_history_list
	8,  // 22: yuhaiin.protos.statistic.service.connections.all_history:output_type -> yuhaiin.protos.statistic.service.all_history_list
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_statistic_grpc_config_proto_init() }
func file_statistic_grpc_config_proto_init() {
	if File_statistic_grpc_config_proto != nil {
		return
	}
	file_statistic_grpc_config_proto_msgTypes[2].OneofWrappers = []any{
		(*notifyData_TotalFlow)(nil),
		(*notifyData_NotifyNewConnections)(nil),
		(*notifyData_NotifyRemoveConnections)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_statistic_grpc_config_proto_rawDesc), len(file_statistic_grpc_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_statistic_grpc_config_proto_goTypes,
		DependencyIndexes: file_statistic_grpc_config_proto_depIdxs,
		MessageInfos:      file_statistic_grpc_config_proto_msgTypes,
	}.Build()
	File_statistic_grpc_config_proto = out.File
	file_statistic_grpc_config_proto_goTypes = nil
	file_statistic_grpc_config_proto_depIdxs = nil
}
