#!/bin/bash

podman run -it --rm \
    -v ${PWD}/tmp:/root/.config/yuhaiin \
    -v ${PWD}:/debug \
    -p 50053:50051 \
    --device=/dev/net/tun \
    --sysctl=net.ipv6.conf.all.disable_ipv6=0 \
    --sysctl=net.ipv4.conf.all.src_valid_mark=1 \
    --cap-add=NET_ADMIN \
    localhost/ydebug:latest \
    sh
