// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config/config.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Setting struct {
	BlackIcon            bool       `protobuf:"varint,1,opt,name=BlackIcon,json=black_icon,proto3" json:"BlackIcon,omitempty"`
	IsDNSOverHTTPS       bool       `protobuf:"varint,2,opt,name=IsDNSOverHTTPS,json=is_dns_over_https,proto3" json:"IsDNSOverHTTPS,omitempty"`
	DNSAcrossProxy       bool       `protobuf:"varint,3,opt,name=DNSAcrossProxy,json=dns_across_proxy,proto3" json:"DNSAcrossProxy,omitempty"`
	DnsServer            string     `protobuf:"bytes,4,opt,name=DnsServer,json=dnsServer,proto3" json:"DnsServer,omitempty"`
	DnsSubNet            string     `protobuf:"bytes,5,opt,name=DnsSubNet,json=dns_sub_net,proto3" json:"DnsSubNet,omitempty"`
	Bypass               bool       `protobuf:"varint,6,opt,name=Bypass,json=bypass,proto3" json:"Bypass,omitempty"`
	HttpProxyAddress     string     `protobuf:"bytes,7,opt,name=HttpProxyAddress,json=httpProxyAddress,proto3" json:"HttpProxyAddress,omitempty"`
	Socks5ProxyAddress   string     `protobuf:"bytes,8,opt,name=Socks5ProxyAddress,json=socks5ProxyAddress,proto3" json:"Socks5ProxyAddress,omitempty"`
	RedirProxyAddress    string     `protobuf:"bytes,9,opt,name=RedirProxyAddress,json=redir_proxy_address,proto3" json:"RedirProxyAddress,omitempty"`
	BypassFile           string     `protobuf:"bytes,10,opt,name=BypassFile,json=bypassFile,proto3" json:"BypassFile,omitempty"`
	SsrPath              string     `protobuf:"bytes,11,opt,name=SsrPath,json=ssrPath,proto3" json:"SsrPath,omitempty"`
	DirectDNS            *DirectDNS `protobuf:"bytes,12,opt,name=DirectDNS,json=direct_dns,proto3" json:"DirectDNS,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Setting) Reset()         { *m = Setting{} }
func (m *Setting) String() string { return proto.CompactTextString(m) }
func (*Setting) ProtoMessage()    {}
func (*Setting) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{0}
}

func (m *Setting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Setting.Unmarshal(m, b)
}
func (m *Setting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Setting.Marshal(b, m, deterministic)
}
func (m *Setting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Setting.Merge(m, src)
}
func (m *Setting) XXX_Size() int {
	return xxx_messageInfo_Setting.Size(m)
}
func (m *Setting) XXX_DiscardUnknown() {
	xxx_messageInfo_Setting.DiscardUnknown(m)
}

var xxx_messageInfo_Setting proto.InternalMessageInfo

func (m *Setting) GetBlackIcon() bool {
	if m != nil {
		return m.BlackIcon
	}
	return false
}

func (m *Setting) GetIsDNSOverHTTPS() bool {
	if m != nil {
		return m.IsDNSOverHTTPS
	}
	return false
}

func (m *Setting) GetDNSAcrossProxy() bool {
	if m != nil {
		return m.DNSAcrossProxy
	}
	return false
}

func (m *Setting) GetDnsServer() string {
	if m != nil {
		return m.DnsServer
	}
	return ""
}

func (m *Setting) GetDnsSubNet() string {
	if m != nil {
		return m.DnsSubNet
	}
	return ""
}

func (m *Setting) GetBypass() bool {
	if m != nil {
		return m.Bypass
	}
	return false
}

func (m *Setting) GetHttpProxyAddress() string {
	if m != nil {
		return m.HttpProxyAddress
	}
	return ""
}

func (m *Setting) GetSocks5ProxyAddress() string {
	if m != nil {
		return m.Socks5ProxyAddress
	}
	return ""
}

func (m *Setting) GetRedirProxyAddress() string {
	if m != nil {
		return m.RedirProxyAddress
	}
	return ""
}

func (m *Setting) GetBypassFile() string {
	if m != nil {
		return m.BypassFile
	}
	return ""
}

func (m *Setting) GetSsrPath() string {
	if m != nil {
		return m.SsrPath
	}
	return ""
}

func (m *Setting) GetDirectDNS() *DirectDNS {
	if m != nil {
		return m.DirectDNS
	}
	return nil
}

type DirectDNS struct {
	Host                 string   `protobuf:"bytes,1,opt,name=Host,json=host,proto3" json:"Host,omitempty"`
	DOH                  bool     `protobuf:"varint,2,opt,name=DOH,json=doh,proto3" json:"DOH,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirectDNS) Reset()         { *m = DirectDNS{} }
func (m *DirectDNS) String() string { return proto.CompactTextString(m) }
func (*DirectDNS) ProtoMessage()    {}
func (*DirectDNS) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{1}
}

func (m *DirectDNS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectDNS.Unmarshal(m, b)
}
func (m *DirectDNS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectDNS.Marshal(b, m, deterministic)
}
func (m *DirectDNS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectDNS.Merge(m, src)
}
func (m *DirectDNS) XXX_Size() int {
	return xxx_messageInfo_DirectDNS.Size(m)
}
func (m *DirectDNS) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectDNS.DiscardUnknown(m)
}

var xxx_messageInfo_DirectDNS proto.InternalMessageInfo

func (m *DirectDNS) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *DirectDNS) GetDOH() bool {
	if m != nil {
		return m.DOH
	}
	return false
}

func init() {
	proto.RegisterType((*Setting)(nil), "yuhaiin.api.Setting")
	proto.RegisterType((*DirectDNS)(nil), "yuhaiin.api.DirectDNS")
}

func init() {
	proto.RegisterFile("config/config.proto", fileDescriptor_cc332a44e926b360)
}

var fileDescriptor_cc332a44e926b360 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xc1, 0x6a, 0xdb, 0x40,
	0x10, 0x86, 0x71, 0xed, 0xda, 0xd1, 0xb8, 0x04, 0x67, 0x02, 0x61, 0x0f, 0x6d, 0x30, 0x29, 0x05,
	0xb7, 0x07, 0x99, 0xb6, 0xe4, 0x01, 0x6c, 0x44, 0x51, 0x2e, 0x8a, 0xd1, 0xe6, 0xd4, 0x8b, 0x58,
	0xad, 0x36, 0xd6, 0x92, 0x74, 0x57, 0xec, 0xac, 0x4c, 0xfd, 0x96, 0x7d, 0xa4, 0xa2, 0x95, 0x1a,
	0x92, 0xe6, 0x24, 0xcd, 0xff, 0x7f, 0x33, 0x23, 0xf1, 0x0f, 0x9c, 0x4b, 0x6b, 0xee, 0xf5, 0x7e,
	0xdd, 0x3f, 0xe2, 0xc6, 0x59, 0x6f, 0x71, 0x7e, 0x6c, 0x6b, 0xa1, 0xb5, 0x89, 0x45, 0xa3, 0xaf,
	0xfe, 0x8c, 0x61, 0xc6, 0x95, 0xf7, 0xda, 0xec, 0xf1, 0x03, 0x44, 0xdb, 0x47, 0x21, 0x1f, 0x6e,
	0xa4, 0x35, 0x6c, 0xb4, 0x1c, 0xad, 0x4e, 0x72, 0x28, 0x3b, 0xa1, 0xd0, 0xd2, 0x1a, 0xfc, 0x0c,
	0xa7, 0x37, 0x94, 0x64, 0xfc, 0xf6, 0xa0, 0x5c, 0x7a, 0x77, 0xb7, 0xe3, 0xec, 0x4d, 0x60, 0xce,
	0x34, 0x15, 0x95, 0xa1, 0xc2, 0x1e, 0x94, 0x2b, 0x6a, 0xef, 0x1b, 0xc2, 0x15, 0x9c, 0x26, 0x19,
	0xdf, 0x48, 0x67, 0x89, 0x76, 0xce, 0xfe, 0x3e, 0xb2, 0x71, 0x40, 0x17, 0x1d, 0x27, 0x82, 0x5c,
	0x34, 0x9d, 0x8e, 0xef, 0x21, 0x4a, 0x0c, 0x71, 0xe5, 0x0e, 0xca, 0xb1, 0xc9, 0x72, 0xb4, 0x8a,
	0xf2, 0xa8, 0xfa, 0x27, 0xe0, 0x65, 0xef, 0xb6, 0x65, 0xa6, 0x3c, 0x7b, 0x1b, 0xdc, 0x79, 0x37,
	0x82, 0xda, 0xb2, 0x30, 0xca, 0xe3, 0x05, 0x4c, 0xb7, 0xc7, 0x46, 0x10, 0xb1, 0x69, 0x98, 0x3f,
	0x2d, 0x43, 0x85, 0x5f, 0x60, 0x91, 0x7a, 0xdf, 0x84, 0xd5, 0x9b, 0xaa, 0x72, 0x8a, 0x88, 0xcd,
	0x42, 0xfb, 0xa2, 0xfe, 0x4f, 0xc7, 0x18, 0x90, 0x5b, 0xf9, 0x40, 0xd7, 0x2f, 0xe8, 0x93, 0x40,
	0x23, 0xbd, 0x72, 0x30, 0x86, 0xb3, 0x5c, 0x55, 0xda, 0xbd, 0xc0, 0xa3, 0x80, 0x9f, 0xbb, 0xce,
	0xe8, 0xff, 0xac, 0x10, 0x03, 0x7f, 0x09, 0xd0, 0x7f, 0xe3, 0x0f, 0xfd, 0xa8, 0x18, 0x04, 0x10,
	0xca, 0x27, 0x05, 0x19, 0xcc, 0x38, 0xb9, 0x9d, 0xf0, 0x35, 0x9b, 0x07, 0x73, 0x46, 0x7d, 0x89,
	0xd7, 0x10, 0x25, 0xda, 0x29, 0xe9, 0x93, 0x8c, 0xb3, 0x77, 0xcb, 0xd1, 0x6a, 0xfe, 0xed, 0x22,
	0x7e, 0x16, 0x5e, 0xfc, 0xe4, 0xe6, 0x50, 0x85, 0xd7, 0x2e, 0x87, 0xab, 0xaf, 0xcf, 0xda, 0x10,
	0x61, 0x92, 0x5a, 0xf2, 0x21, 0xce, 0x28, 0x9f, 0xd4, 0x96, 0x3c, 0x2e, 0x60, 0x9c, 0xdc, 0xa6,
	0x43, 0x7a, 0xe3, 0xca, 0xd6, 0xdb, 0x4f, 0x3f, 0x3f, 0xee, 0xb5, 0xaf, 0xdb, 0x32, 0x96, 0xf6,
	0xd7, 0x7a, 0x43, 0xad, 0xb7, 0xae, 0xbd, 0x17, 0xeb, 0x61, 0xd9, 0x70, 0x3f, 0xe5, 0x34, 0x1c,
	0xd0, 0xf7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x5d, 0xac, 0x95, 0x57, 0x02, 0x00, 0x00,
}
