// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v6.30.1
// source: config/log/log.proto

package log

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_verbose LogLevel = 0
	LogLevel_debug   LogLevel = 1
	LogLevel_info    LogLevel = 2
	LogLevel_warning LogLevel = 3
	LogLevel_error   LogLevel = 4
	LogLevel_fatal   LogLevel = 5
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "verbose",
		1: "debug",
		2: "info",
		3: "warning",
		4: "error",
		5: "fatal",
	}
	LogLevel_value = map[string]int32{
		"verbose": 0,
		"debug":   1,
		"info":    2,
		"warning": 3,
		"error":   4,
		"fatal":   5,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_config_log_log_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_config_log_log_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Logcat struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Level              LogLevel               `protobuf:"varint,1,opt,name=level,enum=yuhaiin.log.LogLevel"`
	xxx_hidden_Save               bool                   `protobuf:"varint,2,opt,name=save"`
	xxx_hidden_IgnoreTimeoutError bool                   `protobuf:"varint,3,opt,name=ignore_timeout_error"`
	xxx_hidden_IgnoreDnsError     bool                   `protobuf:"varint,4,opt,name=ignore_dns_error"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Logcat) Reset() {
	*x = Logcat{}
	mi := &file_config_log_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logcat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logcat) ProtoMessage() {}

func (x *Logcat) ProtoReflect() protoreflect.Message {
	mi := &file_config_log_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Logcat) GetLevel() LogLevel {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Level
		}
	}
	return LogLevel_verbose
}

func (x *Logcat) GetSave() bool {
	if x != nil {
		return x.xxx_hidden_Save
	}
	return false
}

func (x *Logcat) GetIgnoreTimeoutError() bool {
	if x != nil {
		return x.xxx_hidden_IgnoreTimeoutError
	}
	return false
}

func (x *Logcat) GetIgnoreDnsError() bool {
	if x != nil {
		return x.xxx_hidden_IgnoreDnsError
	}
	return false
}

func (x *Logcat) SetLevel(v LogLevel) {
	x.xxx_hidden_Level = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Logcat) SetSave(v bool) {
	x.xxx_hidden_Save = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Logcat) SetIgnoreTimeoutError(v bool) {
	x.xxx_hidden_IgnoreTimeoutError = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Logcat) SetIgnoreDnsError(v bool) {
	x.xxx_hidden_IgnoreDnsError = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *Logcat) HasLevel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Logcat) HasSave() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Logcat) HasIgnoreTimeoutError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Logcat) HasIgnoreDnsError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Logcat) ClearLevel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Level = LogLevel_verbose
}

func (x *Logcat) ClearSave() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Save = false
}

func (x *Logcat) ClearIgnoreTimeoutError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_IgnoreTimeoutError = false
}

func (x *Logcat) ClearIgnoreDnsError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_IgnoreDnsError = false
}

type Logcat_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Level              *LogLevel
	Save               *bool
	IgnoreTimeoutError *bool
	IgnoreDnsError     *bool
}

func (b0 Logcat_builder) Build() *Logcat {
	m0 := &Logcat{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Level != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Level = *b.Level
	}
	if b.Save != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Save = *b.Save
	}
	if b.IgnoreTimeoutError != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_IgnoreTimeoutError = *b.IgnoreTimeoutError
	}
	if b.IgnoreDnsError != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_IgnoreDnsError = *b.IgnoreDnsError
	}
	return m0
}

var File_config_log_log_proto protoreflect.FileDescriptor

var file_config_log_log_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x6c, 0x6f, 0x67, 0x2f, 0x6c, 0x6f, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x79, 0x75, 0x68, 0x61, 0x69, 0x69, 0x6e, 0x2e,
	0x6c, 0x6f, 0x67, 0x1a, 0x21, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x5f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaa, 0x01, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x63, 0x61,
	0x74, 0x12, 0x2c, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x16, 0x2e, 0x79, 0x75, 0x68, 0x61, 0x69, 0x69, 0x6e, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x6c,
	0x6f, 0x67, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x61, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x73,
	0x61, 0x76, 0x65, 0x12, 0x32, 0x0a, 0x14, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x14, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x10, 0x69, 0x67, 0x6e, 0x6f, 0x72,
	0x65, 0x5f, 0x64, 0x6e, 0x73, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x10, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x64, 0x6e, 0x73, 0x5f, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x2a, 0x50, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x0b, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x64, 0x65, 0x62, 0x75, 0x67, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0x03, 0x12,
	0x09, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x66, 0x61,
	0x74, 0x61, 0x6c, 0x10, 0x05, 0x42, 0x3c, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x73, 0x75, 0x74, 0x6f, 0x72, 0x75, 0x66, 0x61, 0x2f, 0x79, 0x75,
	0x68, 0x61, 0x69, 0x69, 0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x6c, 0x6f, 0x67, 0x92, 0x03, 0x05, 0xd2, 0x3e,
	0x02, 0x10, 0x03, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70, 0xe8, 0x07,
})

var file_config_log_log_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_config_log_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_config_log_log_proto_goTypes = []any{
	(LogLevel)(0),  // 0: yuhaiin.log.log_level
	(*Logcat)(nil), // 1: yuhaiin.log.logcat
}
var file_config_log_log_proto_depIdxs = []int32{
	0, // 0: yuhaiin.log.logcat.level:type_name -> yuhaiin.log.log_level
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_config_log_log_proto_init() }
func file_config_log_log_proto_init() {
	if File_config_log_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_log_log_proto_rawDesc), len(file_config_log_log_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_log_log_proto_goTypes,
		DependencyIndexes: file_config_log_log_proto_depIdxs,
		EnumInfos:         file_config_log_log_proto_enumTypes,
		MessageInfos:      file_config_log_log_proto_msgTypes,
	}.Build()
	File_config_log_log_proto = out.File
	file_config_log_log_proto_goTypes = nil
	file_config_log_log_proto_depIdxs = nil
}
