package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	input := flag.String("input", "pkg/contract", "Go contract directory")
	output := flag.String("output", "", "TypeScript output path")
	flag.Parse()
	if *output == "" {
		panic("-output is required")
	}
	content, err := render(*input)
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(*output, content, 0o644); err != nil {
		panic(err)
	}
}

func render(root string) ([]byte, error) {
	packages := map[string][]string{}
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil || entry.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return err
		}
		packages[filepath.Base(filepath.Dir(path))] = append(packages[filepath.Base(filepath.Dir(path))], path)
		return nil
	})
	if err != nil {
		return nil, err
	}
	names := make([]string, 0, len(packages))
	for name := range packages {
		names = append(names, name)
	}
	sort.Strings(names)
	var out bytes.Buffer
	out.WriteString("// Code generated by cmd/contract-ts-gen; DO NOT EDIT.\n\nexport namespace Go {\n")
	for _, name := range names {
		fmt.Fprintf(&out, "  export namespace %s {\n", sanitize(name))
		for _, path := range packages[name] {
			file, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.ParseComments)
			if err != nil {
				return nil, err
			}
			for _, decl := range file.Decls {
				gen, ok := decl.(*ast.GenDecl)
				if !ok || gen.Tok != token.TYPE {
					continue
				}
				for _, spec := range gen.Specs {
					if err := writeType(&out, spec.(*ast.TypeSpec), "    "); err != nil {
						return nil, err
					}
				}
			}
		}
		out.WriteString("  }\n")
	}
	out.WriteString("}\n")
	return out.Bytes(), nil
}

func writeType(out *bytes.Buffer, spec *ast.TypeSpec, indent string) error {
	switch value := spec.Type.(type) {
	case *ast.StructType:
		fmt.Fprintf(out, "%sexport interface %s {\n", indent, spec.Name.Name)
		for _, field := range value.Fields.List {
			if len(field.Names) == 0 {
				continue
			}
			name, optional := jsonName(field)
			if name == "-" {
				continue
			}
			if optional || isPointer(field.Type) {
				name += "?"
			}
			fmt.Fprintf(out, "%s  %s: %s;\n", indent, name, tsType(field.Type))
		}
		fmt.Fprintf(out, "%s}\n", indent)
	case *ast.InterfaceType:
		fmt.Fprintf(out, "%sexport type %s = unknown;\n", indent, spec.Name.Name)
	default:
		fmt.Fprintf(out, "%sexport type %s = %s;\n", indent, spec.Name.Name, tsType(value))
	}
	return nil
}

func jsonName(field *ast.Field) (string, bool) {
	if field.Tag == nil {
		return field.Names[0].Name, false
	}
	tag, err := strconv.Unquote(field.Tag.Value)
	if err != nil {
		return field.Names[0].Name, false
	}
	value := reflectTag(tag, "json")
	if value == "" {
		return field.Names[0].Name, false
	}
	parts := strings.Split(value, ",")
	return parts[0], strings.Contains(value, "omitempty") || strings.Contains(value, "omitzero")
}

func reflectTag(tag, key string) string {
	for _, part := range strings.Split(tag, " ") {
		if strings.HasPrefix(part, key+":") {
			value, _ := strconv.Unquote(strings.TrimPrefix(part, key+":"))
			return value
		}
	}
	return ""
}
func isPointer(expr ast.Expr) bool { _, ok := expr.(*ast.StarExpr); return ok }
func tsType(expr ast.Expr) string {
	switch value := expr.(type) {
	case *ast.Ident:
		switch value.Name {
		case "string":
			return "string"
		case "bool":
			return "boolean"
		case "byte", "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64":
			return "number"
		case "any":
			return "unknown"
		default:
			return value.Name
		}
	case *ast.ArrayType:
		return tsType(value.Elt) + "[]"
	case *ast.StarExpr:
		return tsType(value.X)
	case *ast.MapType:
		return "Record<" + tsType(value.Key) + ", " + tsType(value.Value) + ">"
	case *ast.SelectorExpr:
		packageName := selectorName(value.X)
		if packageName == "time" && value.Sel.Name == "Time" {
			return "string"
		}
		return "Go." + strings.TrimPrefix(packageName, "contract") + "." + value.Sel.Name
	case *ast.InterfaceType:
		return "unknown"
	case *ast.StructType:
		return "Record<string, unknown>"
	default:
		return "unknown"
	}
}
func selectorName(expr ast.Expr) string {
	if ident, ok := expr.(*ast.Ident); ok {
		return sanitize(ident.Name)
	}
	return "unknown"
}
func sanitize(name string) string {
	return strings.Map(func(r rune) rune {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_' {
			return r
		}
		return '_'
	}, name)
}
