// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: node/node.proto

package node

import (
	point "github.com/Asutorufa/yuhaiin/pkg/protos/node/point"
	subscribe "github.com/Asutorufa/yuhaiin/pkg/protos/node/subscribe"
	tag "github.com/Asutorufa/yuhaiin/pkg/protos/node/tag"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state              protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_Tcp     *point.Point               `protobuf:"bytes,4,opt,name=tcp"`
	xxx_hidden_Udp     *point.Point               `protobuf:"bytes,5,opt,name=udp"`
	xxx_hidden_Links   map[string]*subscribe.Link `protobuf:"bytes,2,rep,name=links" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Manager *Manager                   `protobuf:"bytes,3,opt,name=manager"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_node_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Node) GetTcp() *point.Point {
	if x != nil {
		return x.xxx_hidden_Tcp
	}
	return nil
}

func (x *Node) GetUdp() *point.Point {
	if x != nil {
		return x.xxx_hidden_Udp
	}
	return nil
}

func (x *Node) GetLinks() map[string]*subscribe.Link {
	if x != nil {
		return x.xxx_hidden_Links
	}
	return nil
}

func (x *Node) GetManager() *Manager {
	if x != nil {
		return x.xxx_hidden_Manager
	}
	return nil
}

func (x *Node) SetTcp(v *point.Point) {
	x.xxx_hidden_Tcp = v
}

func (x *Node) SetUdp(v *point.Point) {
	x.xxx_hidden_Udp = v
}

func (x *Node) SetLinks(v map[string]*subscribe.Link) {
	x.xxx_hidden_Links = v
}

func (x *Node) SetManager(v *Manager) {
	x.xxx_hidden_Manager = v
}

func (x *Node) HasTcp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tcp != nil
}

func (x *Node) HasUdp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Udp != nil
}

func (x *Node) HasManager() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Manager != nil
}

func (x *Node) ClearTcp() {
	x.xxx_hidden_Tcp = nil
}

func (x *Node) ClearUdp() {
	x.xxx_hidden_Udp = nil
}

func (x *Node) ClearManager() {
	x.xxx_hidden_Manager = nil
}

type Node_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Tcp     *point.Point
	Udp     *point.Point
	Links   map[string]*subscribe.Link
	Manager *Manager
}

func (b0 Node_builder) Build() *Node {
	m0 := &Node{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Tcp = b.Tcp
	x.xxx_hidden_Udp = b.Udp
	x.xxx_hidden_Links = b.Links
	x.xxx_hidden_Manager = b.Manager
	return m0
}

type Manager struct {
	state            protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Nodes map[string]*point.Point `protobuf:"bytes,3,rep,name=nodes" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Tags  map[string]*tag.Tags    `protobuf:"bytes,4,rep,name=tags" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Manager) Reset() {
	*x = Manager{}
	mi := &file_node_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manager) ProtoMessage() {}

func (x *Manager) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Manager) GetNodes() map[string]*point.Point {
	if x != nil {
		return x.xxx_hidden_Nodes
	}
	return nil
}

func (x *Manager) GetTags() map[string]*tag.Tags {
	if x != nil {
		return x.xxx_hidden_Tags
	}
	return nil
}

func (x *Manager) SetNodes(v map[string]*point.Point) {
	x.xxx_hidden_Nodes = v
}

func (x *Manager) SetTags(v map[string]*tag.Tags) {
	x.xxx_hidden_Tags = v
}

type Manager_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Nodes map[string]*point.Point
	Tags  map[string]*tag.Tags
}

func (b0 Manager_builder) Build() *Manager {
	m0 := &Manager{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Nodes = b.Nodes
	x.xxx_hidden_Tags = b.Tags
	return m0
}

var File_node_node_proto protoreflect.FileDescriptor

const file_node_node_proto_rawDesc = "" +
	"\n" +
	"\x0fnode/node.proto\x12\fyuhaiin.node\x1a\x16node/point/point.proto\x1a\x1enode/subscribe/subscribe.proto\x1a\x12node/tag/tag.proto\x1a!google/protobuf/go_features.proto\"\x8f\x02\n" +
	"\x04node\x12&\n" +
	"\x03tcp\x18\x04 \x01(\v2\x14.yuhaiin.point.pointR\x03tcp\x12&\n" +
	"\x03udp\x18\x05 \x01(\v2\x14.yuhaiin.point.pointR\x03udp\x123\n" +
	"\x05links\x18\x02 \x03(\v2\x1d.yuhaiin.node.node.LinksEntryR\x05links\x12/\n" +
	"\amanager\x18\x03 \x01(\v2\x15.yuhaiin.node.managerR\amanager\x1aQ\n" +
	"\n" +
	"LinksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.yuhaiin.subscribe.linkR\x05value:\x028\x01\"\xa2\x02\n" +
	"\amanager\x126\n" +
	"\x05nodes\x18\x03 \x03(\v2 .yuhaiin.node.manager.NodesEntryR\x05nodes\x123\n" +
	"\x04tags\x18\x04 \x03(\v2\x1f.yuhaiin.node.manager.TagsEntryR\x04tags\x1aN\n" +
	"\n" +
	"NodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.yuhaiin.point.pointR\x05value:\x028\x01\x1aJ\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.yuhaiin.tag.tagsR\x05value:\x028\x01J\x04\b\x02\x10\x03R\bgroupsV2B6Z,github.com/Asutorufa/yuhaiin/pkg/protos/node\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_node_node_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_node_node_proto_goTypes = []any{
	(*Node)(nil),           // 0: yuhaiin.node.node
	(*Manager)(nil),        // 1: yuhaiin.node.manager
	nil,                    // 2: yuhaiin.node.node.LinksEntry
	nil,                    // 3: yuhaiin.node.manager.NodesEntry
	nil,                    // 4: yuhaiin.node.manager.TagsEntry
	(*point.Point)(nil),    // 5: yuhaiin.point.point
	(*subscribe.Link)(nil), // 6: yuhaiin.subscribe.link
	(*tag.Tags)(nil),       // 7: yuhaiin.tag.tags
}
var file_node_node_proto_depIdxs = []int32{
	5, // 0: yuhaiin.node.node.tcp:type_name -> yuhaiin.point.point
	5, // 1: yuhaiin.node.node.udp:type_name -> yuhaiin.point.point
	2, // 2: yuhaiin.node.node.links:type_name -> yuhaiin.node.node.LinksEntry
	1, // 3: yuhaiin.node.node.manager:type_name -> yuhaiin.node.manager
	3, // 4: yuhaiin.node.manager.nodes:type_name -> yuhaiin.node.manager.NodesEntry
	4, // 5: yuhaiin.node.manager.tags:type_name -> yuhaiin.node.manager.TagsEntry
	6, // 6: yuhaiin.node.node.LinksEntry.value:type_name -> yuhaiin.subscribe.link
	5, // 7: yuhaiin.node.manager.NodesEntry.value:type_name -> yuhaiin.point.point
	7, // 8: yuhaiin.node.manager.TagsEntry.value:type_name -> yuhaiin.tag.tags
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_node_node_proto_init() }
func file_node_node_proto_init() {
	if File_node_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_node_proto_rawDesc), len(file_node_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_node_proto_goTypes,
		DependencyIndexes: file_node_node_proto_depIdxs,
		MessageInfos:      file_node_node_proto_msgTypes,
	}.Build()
	File_node_node_proto = out.File
	file_node_node_proto_goTypes = nil
	file_node_node_proto_depIdxs = nil
}
